POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "josejose2",
  "password": "123456"
}

### Login del usuario
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "josejose2",
  "password": "123456"
}


### Login del usuario
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "josejose",
  "password": "123456"
}


### Crear tarea
POST http://localhost:5000/api/tasks
Content-Type: application/json
Authorization: Bearer token

{
  "title": "Tarea de prueba",
  "description": "Esta es una tarea de ejemplo"
}

### Listar tareas del usuario autenticado
GET http://localhost:5000/api/tasks
Authorization: Bearer token


### Listar tareas del usuario autenticado
GET http://localhost:5000/api/tasks
Authorization: Bearer token

### Editar tarea (reemplaza :taskId por el ID real)
PUT http://localhost:5000/api/tasks/5
Content-Type: application/json
Authorization: Bearer token

{
  "title": "Título actualizado",
  "description": "Descripción actualizada",
  "status": "en_progreso"
}

### Eliminar tarea
DELETE http://localhost:5000/api/tasks/1
Authorization: Bearer token
